[package]
name = "olympian"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstar = "0.9.3"
faer-core = "0.9"
faer-lu = "0.9"
dyn-stack = "0.9"
reborrow = "0.5"